EXPORT_STAGE_TOPOLOGY_JSON = False
STAGE_TOPOLOGY_JSON_PATH = "/home/netai-sys/cs-project/Aquacast/extensions/aquacast.aquacast_composer/stage_topology.json"

ENABLE_FISH_SWIMMING = True
FISH_NAME_PREFIX = "Fish_"
WATER_PRIM_PATH = "/Root/FishTanks/Contents/Tank/InWater/MetalTank/Water"
FISH_USE_STAGE_TOPOLOGY_JSON = True
FISH_INIT_RETRY_SECONDS = 1.0

# Fish movement is scaled by the detected Water cylinder radius.
FISH_SWIM_SPEED_RADIUS_PER_SECOND = 0.12
FISH_DIRECTION_LERP_RATE = 4.0
FISH_MAX_TURN_RADIANS_PER_SECOND = 1.8
FISH_BOUNDARY_START_RATIO = 0.68
FISH_BOUNDARY_MARGIN_RATIO = 0.12
FISH_SEPARATION_RADIUS_RATIO = 0.18
FISH_COHESION_WEIGHT = 0.18
FISH_ALIGNMENT_WEIGHT = 0.25
FISH_SEPARATION_WEIGHT = 0.42
FISH_WANDER_WEIGHT = 0.20
FISH_BOUNDARY_WEIGHT = 1.35
FISH_VERTICAL_WANDER_WEIGHT = 0.12
